### ISSUE TITLE
parse_string_unsafe() fails to parse strings with Bit or Byte unit

### ISSUE THREAD

**Issue by Mercury37** [tbielawa/bitmath#106]
### Expected behaviour
I was expecting _parse_string_unsafe()_ to parse all of the following units, but at the very least the ones that _parse_string()_ can parse:
- b
- bit
- Bit
- bits
- Bits
- B
- byte
- Byte
- bytes
- Bytes
  
### Actual behaviour
_parse_string_unsafe()_ fails for all strings consisting of a number and any of the above units:
```
parse_string_unsafe("1 b")
```
Results in an error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\Lib\site-packages\bitmath\__init__.py", line 1552, in parse_string_unsafe
    raise ValueError("The unit %s is not a valid bitmath unit" % unit)
ValueError: The unit B is not a valid bitmath unit
```

Similarly:

```
parse_string_unsafe("1 Byte")
```
Produces:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\Lib\site-packages\bitmath\__init__.py", line 1552, in parse_string_unsafe
    raise ValueError("The unit %s is not a valid bitmath unit" % unit)
ValueError: The unit ByteB is not a valid bitmath unit
```
  
The other units listed behave in the same way.
  
### Versions
* bitmath: 1.3.3.1 (PyPi)
* Windows 10
* Python 3.12.1

**Comment by timlnx** [comment]
Hi there, I see your issue here and I will be looking at things here again soon. 2023 was especially busy for me and I am just now getting settled into a place where I can get back to work here. Thanks for your patience.

**Comment by timlnx** [comment]
This and #93 are going to get knocked out this week

**Comment by timlnx** [comment]
Fixed in the `bitbyte-whatever` branch (to be merged). `parse_string(strict=False)` now explicitly handles lone `B` → `Byte`, lone `b` → `Bit`, and the word forms `bit`/`bits`/`byte`/`bytes` (case-insensitive) instead of raising `ValueError`. Note: `parse_string_unsafe()` is deprecated as of 2.0.0; use `parse_string(strict=False)` instead.
