### ISSUE TITLE
bitmath development requirements cannot be installed on Python 3.6

### ISSUE THREAD

**Issue by kapsh** [tbielawa/bitmath#65]
Description of the issue (include full error messages):

Installation of provided requirements fails on distribute installation.
I guess that the `distribute` package [is deprecated](https://bitbucket.org/tarek/distribute/wiki/Home)

How to reproduce the issue:

```
cd bitmath 
virtualenv -p python3.6 venv
. venv/bin/activate
pip install --user -r requirements-py3.txt
```

How reproducible (every time? intermittently?):

Always.

Version of bitmath effected (git hashes are OK):

57c24e6

Your operating system and Python release-version:

Python 3.6 on Gentoo Linux 

What you expected to happen:

Correct installation. Actually, the package itself installs and runs on this Python version.

What actually happened:

```
Collecting python-coveralls (from -r requirements-py3.txt (line 1))
  Using cached python_coveralls-2.9.1-py2.py3-none-any.whl
Collecting nose (from -r requirements-py3.txt (line 2))
  Using cached nose-1.3.7-py3-none-any.whl
Collecting distribute (from -r requirements-py3.txt (line 3))
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-f115aqub/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/pip-build-f115aqub/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/pip-build-f115aqub/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/tmp/pip-build-f115aqub/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/tmp/pip-build-f115aqub/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/tmp/pip-build-f115aqub/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-f115aqub/distribute/
```

**Comment by tbielawa** [comment]
I've removed the `distribute` dependency from the requirements files. I believe this issue is resolved.
