### ISSUE TITLE
Some tests fail with ModuleNotFoundError: No module named 'mock'

### ISSUE THREAD

**Issue by kapsh** [tbielawa/bitmath#66]
Description of the issue (include full error messages):

4 fails without mock module.

How to reproduce the issue:

```
# create virtualenv and install declared dependencies.
python setup.py test
```

Your operating system and Python release-version:

Python 3.6

What you expected to happen:

What actually happened:

```
======================================================================
ERROR: tests.test_query_device_capacity (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_query_device_capacity
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/kapsh/repos/bitmath/tests/test_query_device_capacity.py", line 33, in <module>
    import mock
ModuleNotFoundError: No module named 'mock'


----------------------------------------------------------------------
Ran 206 tests in 0.026s

FAILED (errors=4)
```

**Comment by kapsh** [comment]
I see two possible ways to fix this: 

1. Create some flexible dependencies and import system so it will use `unittest.mock` when available and third-party `mock` otherwise.
2. Just add latter to requirements.

I would choose 2nd because I'm lazy.
