### ISSUE TITLE
progressbar is mandatory when using argparse integration

### ISSUE THREAD

**Issue by teto** [tbielawa/bitmath#89]
I ma using bitmath 1.3.3.1, and trying to leverage the argparse integration (aka bitmath.integrations.BitmathType) . So I import bitmath.integrations which translates to 
```
Traceback (most recent call last):
  File "/run/user/1000/tmp.IS2Y59J8t6/bin/mptcpanalyzer", line 11, in <module>
    load_entry_point('mptcpanalyzer', 'console_scripts', 'mptcpanalyzer')()
  File "/nix/store/6wihp44ygcykcx1bjc0kly3d4lzx5qj1-python3.7-setuptools-41.2.0/lib/python3.7/site-packages/setuptools-41.2.0-py3.7.egg/pkg_resources/__init__.py", line 489, in load_entry_point
  File "/nix/store/6wihp44ygcykcx1bjc0kly3d4lzx5qj1-python3.7-setuptools-41.2.0/lib/python3.7/site-packages/setuptools-41.2.0-py3.7.egg/pkg_resources/__init__.py", line 2852, in load_entry_point
  File "/nix/store/6wihp44ygcykcx1bjc0kly3d4lzx5qj1-python3.7-setuptools-41.2.0/lib/python3.7/site-packages/setuptools-41.2.0-py3.7.egg/pkg_resources/__init__.py", line 2443, in load
  File "/nix/store/6wihp44ygcykcx1bjc0kly3d4lzx5qj1-python3.7-setuptools-41.2.0/lib/python3.7/site-packages/setuptools-41.2.0-py3.7.egg/pkg_resources/__init__.py", line 2449, in resolve
  File "/home/teto/mptcpanalyzer/mptcpanalyzer/cli.py", line 61, in <module>
    import bitmath.integrations
  File "/run/user/1000/tmp.IS2Y59J8t6/lib/python3.7/site-packages/bitmath/integrations.py", line 29, in <module>
    import progressbar.widgets
ModuleNotFoundError: No module named 'progressbar'
```
(import bitmath.integrations.bmargparse is the same).

I don't want to add progressbar to my environment, it would be cool to allow using the argparse integration without pulling progressbar as well.

**Comment by teto** [comment]
duplicate of https://github.com/tbielawa/bitmath/issues/86 sry
